### ISSUE TITLE
Snackbar stuck on status bar android

### ISSUE THREAD

**Issue by hpi-rifal** [LanarsInc/top-snackbar-flutter#35]
After dismiss snackbar stuck on statusbar android.
Im using ModalProgressHud
In my condition, a modal progress show up and close after that modal close then calling showSnackbar and snackbar dismiss but stuck on statusbar.
if not using modalHud no problem,
![carbon](https://user-images.githubusercontent.com/92301055/178926155-9ed766f3-4c7d-450f-9cc4-b116f05b0096.png)

Note im using newest version 2.1.1

**Comment by vizhan-lanars** [comment]
@hpi-rifal 
Could you provide a minimum project to reproduce that behaviour?

**Comment by vizhan-lanars** [comment]
#43 
Version 3.0.0
