### ISSUE TITLE
Snackbar getting stuck on android status bar

### ISSUE THREAD

**Issue by davetebonfire0302** [LanarsInc/top-snackbar-flutter#42]
I use a bottom navigator and show snackbar when receiving an error. When navigating to different pages while snackbar is show it gets stuck.

![image](https://user-images.githubusercontent.com/114453690/200712447-46a0a35e-d0aa-4134-a1f1-4845ea37d2d2.png)

**Comment by vizhan-lanars** [comment]
Duplicate #35
