### ISSUE TITLE
Verify publisher

### ISSUE THREAD

**Issue by alexeyinkin** [LanarsInc/top-snackbar-flutter#45]
Currently pub.dev shows "Unverified publisher" for this package:

![image](https://user-images.githubusercontent.com/44893228/203217470-bf2e1178-a3d8-40da-a008-581f07273f87.png)

If we use this package, it makes code reviews harder in our company. Can you please verify your publishing account to show your domain name like this?

![image](https://user-images.githubusercontent.com/44893228/203217673-a3b5538d-318b-4d96-b11c-d23c7ec88c36.png)

Here is how to do this: https://dart.dev/tools/pub/verified-publishers

**Comment by vizhan-lanars** [comment]
Done
