### ISSUE TITLE
Update examples in README

### ISSUE THREAD

**Issue by alexeyinkin** [LanarsInc/top-snackbar-flutter#46]
The first example is:

```dart
showTopSnackBar(
    context,
    CustomSnackBar.success(
      message:
          "Good job, your release is successful. Have a nice day",
    ),
);
```

This does not build because the first argument requires `OverlayState` instead of `BuildContext`.
Other examples should be updated too.

**Comment by wH1t3-l0tUs** [comment]
need another example pls

**Comment by rajesh-h** [comment]
I am also having same issue.
My example below worked fine till I upgraded flutter.

```
 showTopSnackBar(
        context,
        const CustomSnackBar.success(
          message: "Successful",
        ),
      );
```

Now I have below message.

The argument type 'BuildContext' can't be assigned to the parameter type 'OverlayState'.

**Comment by rajesh-h** [comment]
@alexeyinkin  any workaround for this?

**Comment by longfit** [comment]
Hi
So am I , facing this problem 
The argument type 'BuildContext' can't be assigned to the parameter type 'OverlayState'.  
when I upgraded to ^3.0.0

**Comment by lopb** [comment]
Any news?

**Comment by Flashelperz** [comment]
Hi,
If you haven't resolve your problem yet.
This is the solution you should apply 

`
OverlayState? state = Overlay.of(context);
`
`
    if (state != null) {
      showTopSnackBar(state, _buildSnackBar(translatedMessage, snackBarType));
    }
`

Just a simple precision

- _buildSnackBar(...) here is a custom method i have written to display specific type of alert so for your work you can just continue using **CustomSnackBar** with their static method (info, success...)

Hope this resolve your problem.

**Comment by lopb** [comment]
@Flashelperz , worked like a charm, thank you very much! :)

**Comment by vizhan-lanars** [comment]
I will update README.md and examples.
Thanks

**Comment by vizhan-lanars** [comment]
#58
