### ISSUE TITLE
All icons are rotated by 32 degrees.

### ISSUE THREAD

**Issue by mhmyesman** [LanarsInc/top-snackbar-flutter#5]
All icons are rotated by 32 degrees, even ones passed as parameters, [here](https://github.com/LanarsInc/top-snackbar-flutter/blob/main/lib/custom_snack_bar.dart#L26).

I think a better feature would be either rotating only default icons, or being able to specify the rotation degree.

**Comment by vizhan-lanars** [comment]
You are able to implement your own child widget for the `showTopSnackBar` function.
The CustomSnackBar is just to show usage and isn't a part of the main functionality of the package.
