### ISSUE TITLE
type 'StatelessObserverElement' is not a subtype of type 'OverlayState'

### ISSUE THREAD

**Issue by wiradikusuma** [LanarsInc/top-snackbar-flutter#50]
I understand that version 3 has a breaking change, "Remove BuildContext in favor of OverlayState", but how to migrate from existing code? `showTopSnackBar()` now throws `type 'StatelessObserverElement' is not a subtype of type 'OverlayState'` in the console.

**Comment by vizhan-lanars** [comment]
Does `Overlay.of(context)` work for U?
