### ISSUE TITLE
How to Set Max Width Top Snackbar

### ISSUE THREAD

**Issue by cliftonlabrum** [LanarsInc/top-snackbar-flutter#53]
This package is super-nice. Thank you!

I've noticed that when using `showTopSnackBar` that it always fills the width of app window when it's displayed. This is fine on a phone, but it's pretty wide on tablets and desktop.

I am passing my own custom widget into the snackbar, but I can't find a way to set a maximum width. I've tried hard-coding the `width` on the container and also setting a `maxWidth` using `BoxContraints` without any luck.

Is it possible to set a max width on this somehow?

**Comment by cliftonlabrum** [comment]
I figured it out. I just had to wrap my custom widget in a `Center` and now I can enforce a `maxWidth`. My widget's structure looks something like:

```
Center(
  child: Container(
    constraints: const BoxConstraints(maxWidth: 350),
    child: ...
  ),
)
```

**Comment by Kerimkullov** [comment]
Just wrap parent container with Center widget
