### ISSUE TITLE
message testStyle doesn't work

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [LanarsInc/top-snackbar-flutter#57]
Доброго ранку

I set the text style in the parameters, but it ignores, in particular, I can’t change the color of the text

Overlay.of(context),
    CustomSnackBar.info(
      borderRadius: CustomRadius.radius(20),
      message: text.isEmpty
          ? L10n.of(context).error
          : '${L10n.of(context).error} $text',
      **textStyle**: TextStyle(
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        color: ColorName.white,
        height: 16,
      ),
      icon: SizedBox(),
      
      Thanks in advance, Перемога за Украиной

**Comment by vizhan-lanars** [comment]
Hi
It's nice to read greetings in Ukrainian. Thank you for supporting.

As for the reported issue: we will check.

**Comment by SviatManiuk** [comment]
Hi!
The problem is that the text is not visible due to the value of 16 for the height property. Have a look at [TextStyle height](https://api.flutter.dev/flutter/painting/TextStyle/height.html)
