### ISSUE TITLE
Need to close previous topSnackBar before showing new one

### ISSUE THREAD

**Issue by nurassylive** [LanarsInc/top-snackbar-flutter#6]
Regular SnackBar has this method to hide current SnackBar - ScaffoldMessenger.of(context).hideCurrentSnackBar();
Is there any function which closes previous one before showing topSnackBar?

**Comment by vizhan-lanars** [comment]
Hi, @nurassylive 
New version update (v1.0.1)
Dismiss the previous snackbar before displaying a new one (snackbars don't overlay each other now).

**Comment by fullflash** [comment]
snackbar still stucks when you call showTopSnackbar very fast and you can able only dismiss the last one other stacked
