### ISSUE TITLE
Resize element

### ISSUE THREAD

**Issue by mrgarciamanuel** [LanarsInc/top-snackbar-flutter#60]
There's a way to resize (heigh) of this top snack bar?, i think it's to large. I may be a bit shorter should be more pretty.

There's not contributing guideline file?

**Comment by vizhan-lanars** [comment]
Hi
> In order to show a CustomSnackBar you need to call a showTopSnackBar function. **You can pass there any widget you want** but we have a CustomSnackBar for example.
