### ISSUE TITLE
Text UI Snackbar has line like overflow

### ISSUE THREAD

**Issue by indratrisnar** [LanarsInc/top-snackbar-flutter#65]
i use custom child to show my snackbar on top. here the result.
![image](https://github.com/LanarsInc/top-snackbar-flutter/assets/65453071/abf0dc55-72fc-42ee-ad9f-5bd7840d1ca8)

here the code:
      Widget notifUI = Container(
        height: 96,
        padding: const EdgeInsets.symmetric(
          horizontal: 20,
          vertical: 24,
        ),
        decoration: BoxDecoration(
          color: const Color(0xffFF2055),
          borderRadius: BorderRadius.circular(20),
        ),
        child: const Text(
          'Failed to checkout. Your wallet has no enough balance moment.',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.w600,
            // height: 1.5,
          ),
        ),
      );

showTopSnackBar(Overlay.of(context), notifUI, persistent: true);

**Comment by vizhan-lanars** [comment]
[Rokasurba](https://github.com/Rokasurba) is right
