### ISSUE TITLE
Timer.periodic not work

### ISSUE THREAD

**Issue by frankcheng2020** [LanarsInc/top-snackbar-flutter#8]
new Timer.periodic(Duration(milliseconds: 10000), (timer) {
      showTopSnackBar(
        context,
        CustomSnackBar.info(
          message:
              "There is some information. You need to do something with that",
        ),
      );
    });

**Comment by vizhan-lanars** [comment]
Hi, @frankcheng2020 
It seems like an issue on your side.
`Timer.periodic()` works.
